spring.application.name=SpringAzureOpenAI

spring.ai.openai.api-key=21SmzLnKA1x6dEJNXVSC1PFGXCDq1XxPqucfq9S9y1eXIejFWGfOJQQJ99CFACHYHv6XJ3w3AAABACOGaAXg
spring.ai.openai.base-url=https://saurav-az-openai.openai.azure.com/
spring.ai.openai.chat.model=sauravazchat

