spring.application.name=SpringAzureOpenAI

spring.ai.openai.api-key=21SmzLnKA1x6dEJNXVSC1PFGXCDq1XxPqucfq9S9y1eXIejFWGfOJQQJ99CFACHYHv6XJ3w3AAABACOGaAXg
spring.ai.openai.base-url=https://saurav-az-openai.openai.azure.com/
spring.ai.openai.chat.model=sauravazchat
spring.ai.openai.embedding.model=sauravazembedding
spring.servlet.multipart.max-file-size= 100MB

spring.ai.vectorstore.azure.url=https://aisearchsauravaz.search.windows.net
spring.ai.vectorstore.azure.api-key=ZQYRcs6CfXw3ihPRbmYHhNTsFlxcDlvf0cCfQja9qxAzSeBhhskp