spring.application.name=SpringAzureOpenAI

spring.ai.openai.api-key=21SmzLnKA1x6dEJNXVSC1PFGXCDq1XxPqucfq9S9y1eXIejFWGfOJQQJ99CFACHYHv6XJ3w3AAABACOGaAXg
spring.ai.openai.base-url=https://saurav-az-openai.openai.azure.com/
spring.ai.openai.chat.model=sauravazchat
spring.ai.openai.embedding.model=sauravazembedding
spring.servlet.multipart.max-file-size= 100MB

spring.ai.vectorstore.azure.url=https://aisearchsauravaz.search.windows.net
spring.ai.vectorstore.azure.api-key=ZQYRcs6CfXw3ihPRbmYHhNTsFlxcDlvf0cCfQja9qxAzSeBhhskp


spring.cloud.azure.cosmos.endpoint=https://cosmosaccsauravazai.documents.azure.com:443/
spring.cloud.azure.cosmos.key=tvmEPh4vynYND0jglILf7xQCNKpp1B3lXIZPFXP3nxMiFpBL1z2ZqTOps2qNmbdUdmb4XfUIYYDmACDbZ62BHg==
spring.cloud.azure.cosmos.database=AI200CosmosDB

spring.datasource.url=jdbc:postgresql://postgre-smp-server.postgres.database.azure.com:5432/AI200
spring.datasource.username=smpadmin
spring.datasource.password=P@ssword23

spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true


kv.url=https://kv-smp-az.vault.azure.net/
azure.mi=f0e754f2-55ee-470a-b373-8102835712fd

sbus.queue=sbus-smpaz-queue
sbus.topic1=sbus-smpaz-top1
sbus.topic2=sbus-smpaz-top2

sbus.topic1.sub1=smpaz-top1-sb1
sbus.topic1.sub2=smpaz-top1-sb2

sbus.topic2.sub1=ampaz-top2-sb1
